//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Device_ESP32C3
{
    
    internal partial class WebResource
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((WebResource.manager == null))
                {
                    WebResource.manager = new System.Resources.ResourceManager("Device_ESP32C3.WebResource", typeof(WebResource).Assembly);
                }
                return WebResource.manager;
            }
        }
        internal static string GetString(WebResource.StringResources id)
        {
            return ((string)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            Index = 30232,
        }
    }
}
